name: 'Terraform apply'
on:
  workflow_dispatch:
  push:
    branches:
      - main
permissions:
  id-token: write
  contents: write
jobs:
  terraform-apply:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          submodules: recursive
          token: ${{ secrets.WORKFLOW_TOKEN }}
      - name: Configure AWS credentials for S3 state file access
        uses: aws-actions/configure-aws-credentials@e7f100cf4c008499ea8adda475de1042d6975c7b # v6.0.2
        with:
          role-to-assume: arn:aws:iam::${{ secrets.MANAGEMENT_ACCOUNT }}:role/MgmtDPBootstrapTerraformGitHubRepositoriesRole
          aws-region: eu-west-2
          role-session-name: TerraformRole
      - name: Terraform apply
        run: |
          terraform init
          terraform apply --auto-approve
        env:
          GITHUB_OWNER: nationalarchives
          GITHUB_TOKEN: ${{ secrets.WORKFLOW_TOKEN }}
